// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Psicologia.Context;

#nullable disable

namespace Psicologiaa.Migrations
{
    [DbContext(typeof(EntidadesDbContext))]
    [Migration("20240304005510_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Psicologiaa.Modelo.DatosPersonales", b =>
                {
                    b.Property<int>("IdDatos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDatos"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDatos");

                    b.ToTable("datosPersonales");
                });

            modelBuilder.Entity("Psicologiaa.Modelo.Evaluacion", b =>
                {
                    b.Property<int>("IdEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvaluacion"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("PacienteIdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("Resultados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEvaluacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEvaluacion");

                    b.HasIndex("PacienteIdPaciente");

                    b.ToTable("evaluacion");
                });

            modelBuilder.Entity("Psicologiaa.Modelo.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<int>("DatosPersonalesIdDatos")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDatos")
                        .HasColumnType("int");

                    b.HasKey("IdPaciente");

                    b.HasIndex("DatosPersonalesIdDatos");

                    b.ToTable("paciente");
                });

            modelBuilder.Entity("Psicologiaa.Modelo.Sesion", b =>
                {
                    b.Property<int>("IdSesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSesion"));

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacienteIdPaciente")
                        .HasColumnType("int");

                    b.Property<DateTime>("TiempoSesion")
                        .HasColumnType("datetime2");

                    b.HasKey("IdSesion");

                    b.HasIndex("PacienteIdPaciente");

                    b.ToTable("sesion");
                });

            modelBuilder.Entity("Psicologiaa.Modelo.Terapeuta", b =>
                {
                    b.Property<int>("IdTerapeuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTerapeuta"));

                    b.Property<int>("DatosPersonalesIdDatos")
                        .HasColumnType("int");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDatos")
                        .HasColumnType("int");

                    b.HasKey("IdTerapeuta");

                    b.HasIndex("DatosPersonalesIdDatos");

                    b.ToTable("terapeuta");
                });

            modelBuilder.Entity("Psicologiaa.Modelo.Evaluacion", b =>
                {
                    b.HasOne("Psicologiaa.Modelo.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteIdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Psicologiaa.Modelo.Paciente", b =>
                {
                    b.HasOne("Psicologiaa.Modelo.DatosPersonales", "DatosPersonales")
                        .WithMany()
                        .HasForeignKey("DatosPersonalesIdDatos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatosPersonales");
                });

            modelBuilder.Entity("Psicologiaa.Modelo.Sesion", b =>
                {
                    b.HasOne("Psicologiaa.Modelo.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteIdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Psicologiaa.Modelo.Terapeuta", b =>
                {
                    b.HasOne("Psicologiaa.Modelo.DatosPersonales", "DatosPersonales")
                        .WithMany()
                        .HasForeignKey("DatosPersonalesIdDatos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatosPersonales");
                });
#pragma warning restore 612, 618
        }
    }
}
